= Experimental Design

The experimental phase was carried out inside a kernel-based virtual machine (KVM) with QEMU/KVM to achieve performance as close as possible to a physical machine (bare-metal), ensuring that the results accurately represent real-world conditions. The operating system used was Windows 11 Pro version 24H2 with OS Build 26100.4652. The hardware specifications were set to be twice the recommended requirements for Windows 11 @microsoft_2023, consisting of an AMD Ryzen 7 5800U processor (1.90 GHz) with 4 cores, each supporting 2 threads; 8 GB of memory; and 128 GB of storage space. This specification was chosen to provide sufficient computational capability for the operating system to run smoothly during the testing process.

The virtual machine was configured with 128 target files across 8 different extensions, with a total size of 977.6 MB. The developed ransomware and crypto-ransomware programs were then placed inside the virtual machine, followed by the installation and configuration of antivirus programs. Communication between the host machine and the virtual machine was established through QEMU Guest Agent to simplify testing and automation. Once the setup was complete, a snapshot of the initial state of the virtual machine was created, ensuring that each testing phase started from identical baseline conditions.

The virtual machine was allowed to run for 30 seconds after restoring the snapshot to ensure all Windows startup background processes had finished before executing the ransomware. Once the ransomware was executed, information such as the number of files successfully corrupted and the execution time was recorded when necessary. If the ransomware program completed execution, the virtual machine was left running for another 30 seconds to check whether the antivirus software detected it. Each test configuration was repeated three times to obtain average values, making the results more representative and reducing potential bias or deviations caused by fluctuations in virtual machine resources.

The antivirus programs chosen to be tested were Windows Defender, Norton AntiVirus Plus, McAfee Antivirus, Malwarebytes Premium Security, and Avast Premium Security. These programs were selected based on the 2024 antivirus trend survey conducted by security.org @personal_antivirus_consumer_usage. Each antivirus was configured with its default settings as recommended by its vendor. For virtual machines that did not require antivirus software, Windows Defender was removed using the windows-defender-remover program developed by ionuttbara @ionuttbara_2025.

Lastly, the evaluation method used in this research includes the success rate of the crypto-ransomware program in bypassing antivirus detection, the number of files successfully encrypted, and the antivirus software's ability to recover the encrypted files.
