= Experimental Design

The experimental phase was carried out inside a kernel-based virtual machine (KVM) with QEMU/KVM to achieve performance as close as possible to a physical machine (bare-metal), ensuring that the results accurately represent real-world conditions. The operating system used was Windows 11 Pro version 24H2 with OS Build 26100.4652. The hardware specifications were set to be twice the recommended requirements for Windows 11 @microsoft_2023, consisting of an AMD Ryzen 7 5800U processor (1.90 GHz) with 4 cores, each supporting 2 threads; 8 GB of memory; and 128 GB of storage space. This specification was chosen to provide sufficient computational capability for the operating system to run smoothly during the testing process.

The virtual machine was configured with 128 target files accross 8 different extensions, totaling 977.6 MB. Multiple antivirus programs were then configured and installed inside the virtual machine, after which the developed ransomware and crypto-ransomware samples were deployed within the guest environment. Communication between the host and guest was facilitated via the QEMU Guest Agent to simplify testing and automation. Upon completing the setup, a snapshot of the virtual machine's initial state was taken so that each test iteration would begin from an identical baseline. Network access was disabled inside the virtual machine to eliminate variability introduced by server-side sample analysis. This approach is appropriate given that server-side analysis typically requires more time than the ransomware's execution window. Although some antivirus products terminate malicious processes before producing analysis results, such behavior may be mitigated by techniques intended to evade static, dynamic, or sandbox analysis.

The virtual machine was allowed to run for 30 seconds after restoring the snapshot to ensure all Windows startup background processes had finished before executing the ransomware. Once the ransomware was executed, information such as the number of files successfully corrupted and the execution time was recorded when necessary. If the ransomware program completed execution, the virtual machine was left running for another 30 seconds to check whether the antivirus software detected it. Each test configuration was repeated three times to obtain average values, making the results more representative and reducing potential bias or deviations caused by fluctuations in virtual machine resources.

The antivirus programs chosen to be tested were Windows Defender, Norton AntiVirus Plus, McAfee Antivirus, Malwarebytes Premium Security, and Avast Premium Security. These programs were selected based on the 2024 antivirus trend survey conducted by security.org @personal_antivirus_consumer_usage. Each antivirus were updated to the latest version and configured with its default out-of-the-box settings, of which the protected folders feature was enabled by default in Avast and Norton. The testing phase (and subsequently its latest signature update date) was conducted on 25 July 2025. For virtual machines that did not require antivirus software, Windows Defender was removed using the windows-defender-remover program developed by ionuttbara @ionuttbara_2025.

Lastly, the evaluation method used in this research includes the success rate of the crypto-ransomware program in bypassing antivirus detection, the number of files successfully encrypted, and the antivirus software's ability to recover the encrypted files.
